### PR TITLE
Added (soft deprecated) `description` method for Error implementation

### PR DESCRIPTION
**Pull request by mboogerd**

### CODE REVIEW

**Comment by mboogerd** [comment]
Issued this PR (for issue #1) in case this was not actually something wrong on my end, and a fix would be helpful. If this isn't the right approach, feel free to close!

**Comment by KizzyCode** [comment]
Looks good; I’ll test it when I got home 😊

**Comment by KizzyCode** [comment]
Merged; ty for your issue and pull request 😄

**Comment by KizzyCode** [comment]
Merged; ty for your issue and pull request 😄

**Pull request merged**
